### ISSUE TITLE
How to pass php_namespace option? (option unknown)

### ISSUE THREAD

**Issue by sagotch** [bramp/protoc-gen-php#18]
I am updating old code using protoc-gen-php which use `option (php).namespace = "........";`, but it seems that it won't work with newest versions of protobuf (3.0.0) and protoc-gen-php.

`option php_namespace = "....."` also gives a unknown option. Is it a problem related to protoc-gen-php?

Proto files syntax is proto2.

**Comment by bramp** [comment]
This project is effectively unmaintained at this point. It might be worth moving to the official PHP compiler: https://github.com/google/protobuf/tree/master/php
